spring:
  profiles:
    active:
      - dev
      
---
server:
  #注册中心的端口号
  port: 7001
spring:
  profiles: dev
eureka:
  server:
   #禁掉eureka服务器的自我保护机制，推荐默认的true，不要禁掉
    enable-self-preservation: true
  instance:
    hostname: eureka7001.com
  client:
    #表示自己不注册到服务中心
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
 
---
server:
  #注册中心的端口号
  port: 7001
spring:
  profiles: test
eureka:
  server:
   #禁掉eureka服务器的自我保护机制，推荐默认的true，不要禁掉
    enable-self-preservation: true
  instance:
    hostname: eureka7001.com
  client:
    #表示自己不注册到服务中心
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    