spring:
  profiles:
    active:
      - dev
      
---

server:
  port: 8201
spring:
  profiles: dev
  application: springcloud-config-client
eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud-config-client
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
    registry-fetch-interval-seconds: 30
 
 ---
 
server:
  port: 8202
spring:
  profiles: dev
  application: springcloud-config-client
eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud-config-client
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-test6.com:7001/eureka/
    registry-fetch-interval-seconds: 30
    
 ---