spring:
  profiles:
    active:
      - dev
      
---
server:
  #注册中心的端口号
  port: 7001
spring:
  profiles: dev
  application: 
    name: springcloud-config-eureka-client
eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud-config-client-dev
    #访问路径可以显示IP地址
    prefer-ip-address: true
    hostname: eureka7001.com
  client:
    #表示自己不注册到服务中心
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    registry-fetch-interval-seconds: 30
 
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud-config-client-test
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
   #表示自己不注册到服务中心
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    registry-fetch-interval-seconds: 30
    