---
#服务器设置
server:
  port: 8001

#数据库连接
spring:
  application:
    name: springcloud
  profiles: dev
  datasource:
    url: jdbc:mysql://49.233.200.30:3306/springcloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root123.
    type: com.alibaba.druid.pool.DruidDataSource

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xinjian.model
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null

eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    registry-fetch-interval-seconds: 30

#actuator监控信息
info:
  app.name: springcloud-provider-dept-8001
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 8001

#数据库连接
spring:
  application:
    name: springcloud
  profiles: test
  datasource:
    url: jdbc:mysql://49.233.200.30:3306/springcloud2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root123.
    type: com.alibaba.druid.pool.DruidDataSource

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xinjian.model
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null

eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    #重命名，自定义服务名称信息
    instance-id: springcloud8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    registry-fetch-interval-seconds: 30

#actuator监控信息
info:
  app.name: springcloud-provider-dept-8001
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
